[package]
name = "pkce_oauth"
version = "0.1.1"
edition = "2021"
authors = ["Bogdanov Anton <kortirso@gmail.com>"]
license = "MIT"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
magnus = { version = "0.7" }
pkce = { version = "0.2.0" }
